### ISSUE TITLE
stuck on loading

### ISSUE THREAD

**Issue by amitaymolko** [raphaelluchini/popcorntime-smarttv#1]
Hi,
I am using https://github.com/seibert-media/sstvapp-utils/blob/master/myapp/index.html
to install the app on my smart tv.

When trying to run the app it just gets stuck on loading app... (before even displaying anything in the app)

i edited both player.js to have my pc ip and started the server.js (no errors)

Tv model: UE46F5500AW

Any idea what i might be doing wrong?

**Comment by raphaelluchini** [comment]
There are some samples in samsung SDK, try to get them, modify and deploy and in your TV!

A good example is:
https://github.com/paynen/RottenTomatoesTV

cheers!
