### ISSUE TITLE
What's coming:

### ISSUE THREAD

**Issue by raphaelluchini** [raphaelluchini/popcorntime-smarttv#10]
A new grunt task which compile your smarttv html5 app and creates a webserver to your tv get the app to install. This feature going to help us to deploy and develop our apps faster, without samsung IDE.

I'm having some problems with the workflow and now I'm focusing in apply this feature in the popcorntime app. Then I will fix our popcorntime server and make it easier to run/develop/deploy

I'm open to receive pull requests, just ask me before what do you want to do and we can discuss your idea and develop :) 

Grunt plugin: https://github.com/raphaelluchini/grunt-samsungstv-packager
Packager dependency: https://github.com/raphaelluchini/samsungstv-packager

Thanks to https://github.com/imgntn

**Comment by vpninfodk** [comment]
I've got a lot of users on http://popcorntime.dk and http://popcorntime.co.il asking for a Samsung Smart TV app, so I'm really happy to see that things are moving forward in this project.  

Have you ever considered funding the project with kickstarter or something similar?

**Comment by PedroMCostaAndrade** [comment]
you could get help from our community on discuss.popcorntime.io ;)

**Comment by vpninfodk** [comment]
Yeah sure, didn't know you were a part of that :)

**Comment by PedroMCostaAndrade** [comment]
i'm not a dev or part of the team, i'm only a user that want to help and if i could redirect every project like this to our discuss, the projects will grow up more easily and will be known by much more people see the topic of remotes, they have helped each other :D
