### ISSUE TITLE
app not installed on TV

### ISSUE THREAD

**Issue by gabonator** [raphaelluchini/popcorntime-smarttv#13]
After deploying and setting the IP address (gateway & dns to the ip address as grunt deploy displayed), the TV does not install anything. Do I need to do something specific with the TV? When opened the ip address in web browser, I got: "Cannot GET /" what indicates that something went wrong.

**Comment by raphaelluchini** [comment]
Are you using `sudo grunt deploy`?

**Comment by robotrono** [comment]
Same here, im testing on windows

**Comment by cajadas** [comment]
If you are trying to access the IP through the browser you are not doing it wrong. To install the app on TV you have to sign in through the developer account, set your ip as an app server and sync apps.

**Comment by robotrono** [comment]
This doesn't work on my Samsung TV, the app was installed fine but can't open

**Comment by pilap82** [comment]
@cajadas when you say "To install the app on TV you have to sign in through the developer account, set your ip as an app server and sync apps"

Does it mean signing in on the TV?
I haven't found any place either on the account.samsung.com website or on the TV. Where / how can I do that ?

thanks, p.

**Comment by cajadas** [comment]
Sorry, i meant "login". You have to launch the Samsung App on the smart hub and there should be a login button on the footer.

Follow the "How to install on my TV" tutorial on the Getting Started section.

**Comment by pilap82** [comment]
thanks @cajadas. I've finally found out (using the guide you are referencing). My only issue at the moment is that I can't create a "develop" account :confused: (the TV says "connecting" but the request doesn't go through).

I'll retry later.

thanks for your feedback!
P.

**Comment by cajadas** [comment]
@pilap82 no prob. you cant create it because it already exists. Just login as refered on the tutorial and you'll be good.
