### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by napster3000** [raphaelluchini/popcorntime-smarttv#2]
Hi, Is there a way to download the client app from "smart tv app store"? How to install it ?

**Comment by stephan-v** [comment]
Yes, I'm wondering the same. Would love to know how to install this.

**Comment by lvitti** [comment]
I would like to know how to compile and install it.
Thx

**Comment by hispan1c** [comment]
@raphaelluchini Can you please help us?

**Comment by lvitti** [comment]
download SDK for Samsung IDE (2012 Main SDK : SDK 3.5.2)
from here: http://www.samsungdforum.com/Devtools/SdkDownload

download the code, open the project with the IDE, and generate the packege. 
Then login in the smart tv with develop account and set the IP address of the PC.

**Comment by napster3000** [comment]
Why you don't deploy this app on the official app store?
Leonardo Pellicciotta
(Mobile)

-----Original Message-----

**Comment by hispan1c** [comment]
It's still a pre-alpha release

**Comment by lvitti** [comment]
I do not think samsung allow this application in the app store

**Comment by hispan1c** [comment]
@xAnubiSx
Did you manage? Is it working?  I followed your steps above but couldnt open it in IDE.

**Comment by napster3000** [comment]
If someone manage to build it, could try to deploy it to the store? Just to give it a try

**Comment by raphaelluchini** [comment]
Hello, this week was really insane in my current job, next week I'll provide a good tutorial for start a develop!, we going to need good improvements and refactor, like subtitles and i18n.

This post could help you guys to install any develop app in your SmartTV
https://www.samsungdforum.com/Guide/art00013/index.html

**Comment by raphaelluchini** [comment]
About deploy as official app, Reading the samsung rules, would be impossible the app be accepted! :(

**Comment by hispan1c** [comment]
If someone would host it on a public IP, it would be easy to install for others via App Sync

**Comment by devnoname120** [comment]
@hispan1c It would require the torrent server to be hosted somewhere, a server that has a good bandwidth. If you find someone who is willing to host the server, it could work; otherwise it's useless to deploy it because the server IP can't be modified afterwards. (except if @raphaelluchini adds an option in the application to change the server IP, so you can easily set your own IP).
