### ISSUE TITLE
How to compile on Eclipse and deploy in my TV?

### ISSUE THREAD

**Issue by pipobizelli** [raphaelluchini/popcorntime-smarttv#3]
Hey man,

I'm wondering if you could teach me how to compile with Eclipse, because i'm a mac OS user and then deploy te app to my smart TV

thanks

**Comment by raphaelluchini** [comment]
Hello,

First of all, study a little bit about Samsung SDK:
https://www.samsungdforum.com/Guide/d08/index.html

Next step you going to need to create a hello world application using the emulator to test your environment.
https://www.samsungdforum.com/Guide/d07/index.html

And of course, deploy, test and check if you TV support 3.5+ SDK
https://www.samsungdforum.com/Guide/art00013/index.html
http://www.samsungdforum.com/Devtools/Spec
http://www.samsung.com/us/support/faq/FAQ00057975/76904/LN46B540P8FXZA

ps: I'm currently using 3.5 SDK and testing directly on my TV, but sometimes I'm using 4.5 SDK for emulator. Samsung only provides emulator starting from 4.5 version

Finally, you are be able to start a develop TV apps.
