### ISSUE TITLE
The app dont work in the Emulator

### ISSUE THREAD

**Issue by pipobizelli** [raphaelluchini/popcorntime-smarttv#4]
Hi,

I have installed the emulator from SDK samsung smart TV, to test the app, because I managed to deploy the app to my TV, but the app did not work. Is it because the server or some configuration I did not do correctly?

I change "app/js/frontend/player.js" line 8 to my IP address and start the server (node server) all this looks fine, but in the Emulator the app don't loads the content.

that I miss something?

thanks

**Comment by raphaelluchini** [comment]
Please, try to deploy the latest version.

For server issues, use this repository:

https://github.com/raphaelluchini/popcorntime-smarttv-server

Thanks
