### ISSUE TITLE
Not working on a Samsung TV Serie D

### ISSUE THREAD

**Issue by devnoname120** [raphaelluchini/popcorntime-smarttv#5]
Hello,

I've successfully started the server on my computer, modified the file to put my IP (which works, I've tested), installed the application on my Samsung Smart TV (packaged with Samsung SDK 3.5), and ran it.

However, only the string "movies" and a search field are displayed, but nothing happens. I tried to click on every button of my controller but nothing worked.

Additional information: the console of the server on my computer is free of any error.

**Comment by bundy-al** [comment]
Hello devnoname120 i have a samsung UE40D6530WS can you telle me please how i make the package on my pc and get it on my samsung tv.
Or can someone help with this please.
Greetz

**Comment by bundy-al** [comment]
Install SDK 3.5 do you have a link for me so i have the right one. 
And howto setup the apache server, can you help also with that. 

And does it work on your Samsung tv ???

Greetz and thank you

Verstuurd vanaf mijn iPhone

> Op 7 okt. 2014 om 21:59 heeft Oscar Miranda notifications@github.com het volgende geschreven:
> 
> Follow the instructions from the main GitHub page.
> Instal SDK 3.5
> There are two softwares in there, Including Apache server.
> Setup the path for the local Apache server in your PC, in order that when
> you make the package, the Module get uploaded into the Apache web folder.
> Then setup the IP of your computer in the same network with the TV,
> allowing it to see your PC as a webserver, so it will pull up the file.zip
> from the webfolder.
> Note that an XML file will be created, containing the details of the
> file.zip.
> Regards
> Oscar
>

**Comment by shmilt** [comment]
@oscarmp4 Thanks for the help! I managed to upload the app to the TV. Can you explain how to build the server app?

**Comment by bundyal** [comment]
@oscarmp4 or shmilt i have download the [2012]Samsung_TV_SDK_Setup(3.5.0) and i am installing now, but i installing now  the apache http server 2.2 , but what must i fill into the network domain, server name and administrator's emailadress ???? 
for all users or only for the current user.

And what must i do after that.

**Comment by shmilt** [comment]
@bundyal I just wrote there something to get through this menu. It had no effect on Apache (for me) and it worked fine.

**Comment by shmilt** [comment]
@oscarmp4 I meant that I uploaded the App to the TV. Server side is still missing, I'm unable to build the server project. So it's not working, but the app is now on the TV.
Where did you get stuck?

**Comment by bundyal** [comment]
Hello i must modified the file to put my IP in it, how must i do that.
And how get i the app on my tv????
And we must also install the apache server, as server ???

**Comment by bundyal** [comment]
oscarmp4 or  shmilt will you help me to make the package and send it to my tv.
maybe you have teamviewer and you can takeover my pc.
greetz

**Comment by bundy-al** [comment]
id 915225607
password  r2x2w4

**Comment by bundy-al** [comment]
ID 915225607
Password pqe344

thank you see you tomorrow

**Comment by bundy-al** [comment]
915225607
44p3sb

**Comment by bundy-al** [comment]
i see you tomorrow
i mail you 
greetz

**Comment by bundy-al** [comment]
Hoi Oscar. 
How late wil you help me??
Let we say over 2 hours. 
For you 13:00
It's for me 19:00
Greetz

Verstuurd vanaf mijn iPhone

> Op 12 okt. 2014 om 22:20 heeft Oscar Miranda notifications@github.com het volgende geschreven:
> 
> Okis, 
> 
> See you tomorrow 
> 
> Got to went out for food 
> 
> From: bundy-al [mailto:notifications@github.com] 
> Sent: Sunday, October 12, 2014 4:13 PM 
> To: raphaelluchini/popcorntime-smarttv 
> Cc: Oscar Miranda 
> Subject: Re: [popcorntime-smarttv] Not working on a Samsung TV Serie D (#5) 
> 
> i see you tomorrow 
> i mail you 
> greetz 
> 
> From: Oscar Miranda 
> Sent: Sunday, October 12, 2014 7:04 PM 
> To: raphaelluchini/popcorntime-smarttv 
> Cc: bundy-al 
> Subject: Re: [popcorntime-smarttv] Not working on a Samsung TV Serie D (#5) 
> 
> send 
> ID & passw 
>

**Comment by bundy-al** [comment]
I'm ready
ID 915225607
Pass 7v8he4

Verstuurd vanaf mijn iPhone

> Op 13 okt. 2014 om 17:21 heeft Oscar Miranda notifications@github.com het volgende geschreven:
> 
> Okay, sounds good to me.
> Just let me know when you'll be there.
> Regards
>

**Comment by bundyal** [comment]
I'm ready 
ID 915225607 
Pass 7v8he4 

Verstuurd vanaf mijn iPhone

> Op 13 okt. 2014 om 17:21 heeft Oscar Miranda notifications@github.com het volgende geschreven:
> 
> Okay, sounds good to me.
> Just let me know when you'll be there.
> Regards
>

**Comment by bundy-al** [comment]
I'm ready 
ID 915225607 
Pass 7v8he4 

Verstuurd vanaf mijn iPhone 

> Op 13 okt. 2014 om 17:21 heeft Oscar Miranda notifications@github.com het volgende geschreven: 
> 
> Okay, sounds good to me. 
> Just let me know when you'll be there. 
> Regards 
> 
> On Mon, Oct 13, 2014 at 11:11 AM, bundy-al notifications@github.com wrote: 
> 
> > Hoi Oscar. 
> > How late wil you help me?? 
> > Let we say over 2 hours. 
> > For you 13:00 
> > It's for me 19:00 
> > Greetz 
> > 
> > Verstuurd vanaf mijn iPhone 
> > 
> > > Op 12 okt. 2014 om 22:20 heeft Oscar Miranda notifications@github.com 
> > > het volgende geschreven: 
> > > 
> > > Okis, 
> > > 
> > > See you tomorrow 
> > > 
> > > Got to went out for food 
> > > 
> > > From: bundy-al [mailto:notifications@github.com] 
> > > Sent: Sunday, October 12, 2014 4:13 PM 
> > > To: raphaelluchini/popcorntime-smarttv
> > > Cc: Oscar Miranda 
> > > Subject: Re: [popcorntime-smarttv] Not working on a Samsung TV Serie D 
> > > (#5) 
> > > 
> > > i see you tomorrow 
> > > i mail you 
> > > greetz 
> > > 
> > > From: Oscar Miranda 
> > > Sent: Sunday, October 12, 2014 7:04 PM 
> > > To: raphaelluchini/popcorntime-smarttv
> > > Cc: bundy-al 
> > > Subject: Re: [popcorntime-smarttv] Not working on a Samsung TV Serie D 
> > > (#5) 
> > > 
> > > send 
> > > ID & passw 
> > > 
> > > On Sun, Oct 12, 2014 at 1:03 PM, bundyal notifications@github.com 
> > > wrote: 
> > > 
> > > > oscarmp4 or shmilt will you help me to make the package and send it to 
> > > > my 
> > > > tv. 
> > > > maybe you have teamviewer and you can takeover my pc. 
> > > > greetz 
> > > > 
> > > > ## 
> > > > 
> > > > Reply to this email directly or view it on GitHub 
> > > > < 
> > > > https://github.com/raphaelluchini/popcorntime-smarttv/issues/5#issuecomment-58809943> 
> > > > 
> > > > . 
> > > > 
> > > > ## 
> > > > 
> > > > Reply to this email directly or view it on GitHub. 
> > > 
> > > ## 
> > > 
> > > Reply to this email directly or view it on GitHub < 
> > > https://github.com/raphaelluchini/popcorntime-smarttv/issues/5#issuecomment-58820560> 
> > > 
> > > ## . 
> > > 
> > > Reply to this email directly or view it on GitHub. 
> > 
> > ## 
> > 
> > Reply to this email directly or view it on GitHub 
> > https://github.com/raphaelluchini/popcorntime-smarttv/issues/5#issuecomment-58906085 
> > . 
> > 
> > — 
> > Reply to this email directly or view it on GitHub.
> > —
> > Reply to this email directly or view it on GitHub.

Verstuurd vanaf mijn iPhone

> Op 13 okt. 2014 om 19:21 heeft bundyal notifications@github.com het volgende geschreven:
> 
> I'm ready 
> ID 915225607 
> Pass 7v8he4 
> 
> Verstuurd vanaf mijn iPhone 
> 
> > Op 13 okt. 2014 om 17:21 heeft Oscar Miranda notifications@github.com het volgende geschreven: 
> > 
> > Okay, sounds good to me. 
> > Just let me know when you'll be there. 
> > Regards 
> >

**Comment by bundy-al** [comment]
Hello Oscar i have now the Samsung smart tv apps project in eclipse. 
But if i want to build i get a build error. 
Will you look tomorrow. 
Greetz

Verstuurd vanaf mijn iPhone

> Op 13 okt. 2014 om 19:21 heeft bundyal notifications@github.com het volgende geschreven:
> 
> I'm ready 
> ID 915225607 
> Pass 7v8he4 
> 
> Verstuurd vanaf mijn iPhone 
> 
> > Op 13 okt. 2014 om 17:21 heeft Oscar Miranda notifications@github.com het volgende geschreven: 
> > 
> > Okay, sounds good to me. 
> > Just let me know when you'll be there. 
> > Regards 
> >

**Comment by devnoname120** [comment]
What's the error?

**Comment by bundyal** [comment]
Errors during the build. 
Errors running builder JavaScript validator on project popcorntime smarttv master. 
Org.eclipse.wst.jsdt.internal.compiler.lookup.problembinding cannot be cast to org.eclipse.wst.jsdt.internal.compiler.lookup.localvariablebinding

I'll be back tomorrow 16:00 time in Nederland. 
If you Will help me. 
Then i send you a mail, when i' m home. 
Greetz

Verstuurd vanaf mijn iPhone

**Comment by bundy-al** [comment]
OK, we can help me now with this error. 
Greetz Nico

Verstuurd vanaf mijn iPhone

**Comment by bundy-al** [comment]
Hoi Oscar i mail you over 1 hour. 
Greetz

Verstuurd vanaf mijn iPhone

> Op 14 okt. 2014 om 17:07 heeft Oscar Miranda notifications@github.com het volgende geschreven:
> 
> Hello Nico
> yes
> Send ID + pass
>

**Comment by bundy-al** [comment]
915225607
zzj149

Verstuurd vanaf mijn iPhone

> Op 14 okt. 2014 om 17:16 heeft Oscar Miranda notifications@github.com het volgende geschreven:
> 
> Sure, not a problem.
> Regards
>

**Comment by bundy-al** [comment]
315jtf

Verstuurd vanaf mijn iPhone

> Op 14 okt. 2014 om 17:16 heeft Oscar Miranda notifications@github.com het volgende geschreven:
> 
> Sure, not a problem.
> Regards
>

**Comment by bundy-al** [comment]
Can you help me 1 minute now 

Verstuurd vanaf mijn iPhone

> Op 14 okt. 2014 om 17:16 heeft Oscar Miranda notifications@github.com het volgende geschreven:
> 
> Sure, not a problem.
> Regards
>

**Comment by bundy-al** [comment]
Hoi Oscar how late wil you upload your pics. 
Greetz

Verstuurd vanaf mijn iPhone

> Op 14 okt. 2014 om 17:16 heeft Oscar Miranda notifications@github.com het volgende geschreven:
> 
> Sure, not a problem.
> Regards
>

**Comment by bundyal** [comment]
aw213t

Verstuurd vanaf mijn iPhone

> Op 15 okt. 2014 om 20:27 heeft Oscar Miranda notifications@github.com het volgende geschreven:
> 
> I got them here, give me ID+pass to transfer to you
>

**Comment by bundyal** [comment]
I'am availabile

Verstuurd vanaf mijn iPhone

> Op 15 okt. 2014 om 20:27 heeft Oscar Miranda notifications@github.com het volgende geschreven:
> 
> I got them here, give me ID+pass to transfer to you
>

**Comment by bundyal** [comment]
Hello how late have you time. 

Verstuurd vanaf mijn iPhone

> Op 15 okt. 2014 om 20:27 heeft Oscar Miranda notifications@github.com het volgende geschreven:
> 
> I got them here, give me ID+pass to transfer to you
>

**Comment by bundy-al** [comment]
OK that's 19:00 in Holland. 

Verstuurd vanaf mijn iPhone

> Op 16 okt. 2014 om 13:46 heeft Oscar Miranda notifications@github.com het volgende geschreven:
> 
> 1pm Miami time
> 
> Sent from Note 2
> 
> <div>-------- Mensaje original --------</div><div>De: bundyal notifications@github.com </div><div>Fecha:10/16/2014 07:44 AM (GMT-05:00) </div><div>A: raphaelluchini/popcorntime-smarttv popcorntime-smarttv@noreply.github.com </div><div>CC: Oscar Miranda oscarmp4@gmail.com </div><div>Asunto: Re: [popcorntime-smarttv] Not working on a Samsung TV Serie D (#5) </div><div>
> </div>Hello how late have you time. 
> 
> Verstuurd vanaf mijn iPhone 
> 
> > Op 15 okt. 2014 om 20:27 heeft Oscar Miranda notifications@github.com het volgende geschreven: 
> > 
> > I got them here, give me ID+pass to transfer to you 
> >

**Comment by bundyal** [comment]
790891155

Verstuurd vanaf mijn iPhone

> Op 16 okt. 2014 om 14:16 heeft bundy-al notifications@github.com het volgende geschreven:
> 
> OK that's 19:00 in Holland. 
> 
> Verstuurd vanaf mijn iPhone 
> 
> > Op 16 okt. 2014 om 13:46 heeft Oscar Miranda notifications@github.com het volgende geschreven: 
> > 
> > 1pm Miami time 
> > 
> > Sent from Note 2 
> > 
> > <div>-------- Mensaje original --------</div><div>De: bundyal notifications@github.com </div><div>Fecha:10/16/2014 07:44 AM (GMT-05:00) </div><div>A: raphaelluchini/popcorntime-smarttv popcorntime-smarttv@noreply.github.com </div><div>CC: Oscar Miranda oscarmp4@gmail.com </div><div>Asunto: Re: [popcorntime-smarttv] Not working on a Samsung TV Serie D (#5) </div><div> 
> > </div>Hello how late have you time. 
> > 
> > Verstuurd vanaf mijn iPhone 
> > 
> > > Op 15 okt. 2014 om 20:27 heeft Oscar Miranda notifications@github.com het volgende geschreven: 
> > > 
> > > I got them here, give me ID+pass to transfer to you 
> > >

**Comment by Flconeyes** [comment]
I'll be available today if decide to work something. Regards

**Comment by bundy-al** [comment]
Before we make contact, i have problems with the tv, i get network or server interference occurred. 
Have you a answer for that. 

Verstuurd vanaf mijn iPhone

**Comment by Flconeyes** [comment]
Yes, but I prefer you write me from an email address, to answer you.
Regards
Oscar

**Comment by bundyal** [comment]
Oscar must i mail you and write you from a emailadres ???
Can i not mail you to your personal mail adres ???

Verstuurd vanaf mijn iPhone

> Op 17 okt. 2014 om 21:15 heeft Oscar Miranda notifications@github.com het volgende geschreven:
> 
> Yes, but I prefer you write me from an email address, to answer you.
> Regards
> Oscar
>

**Comment by Flconeyes** [comment]
mail me from your email, it is Ok. Not from the Forum

**Comment by bundy-al** [comment]
Am i mailing you now good ?? Without the forum. 
Do you have time?
Greetz

Verstuurd vanaf mijn iPhone

> Op 17 okt. 2014 om 21:38 heeft Oscar Miranda notifications@github.com het volgende geschreven:
> 
> mail me from your email, it is Ok. Not from the Forum
>

**Comment by Flconeyes** [comment]
Hello Nico,
How're you?
Yes, I'm available

**Comment by bundyal** [comment]
149827214

Verstuurd vanaf mijn iPhone

> Op 18 okt. 2014 om 20:54 heeft Oscar Miranda notifications@github.com het volgende geschreven:
> 
> Hello Nico,
> How're you?
> Yes, I'm available
>

**Comment by bundyal** [comment]
656269127

Verstuurd vanaf mijn iPhone

> Op 18 okt. 2014 om 20:54 heeft Oscar Miranda notifications@github.com het volgende geschreven:
> 
> Hello Nico,
> How're you?
> Yes, I'm available
>

**Comment by Flconeyes** [comment]
# Solve your Network Interference Occurred:

I posted below about this, but, I will post this here as well.
I had the same issue as you. All devices worked on the internet, and SmartTV did not work.
The fix was to put in Google's DNS IP address, instead of your service providers DNS IP address.
To do this, just go to "Tools" and your network settings. Change the DNS IP Address from auto to manual, and enter either 8.8.8.8 or 8.8.4.4.

# Smart TV works perfectly now.

Regards
Me

**Comment by bundyal** [comment]
Oscar are you availabile

Verstuurd vanaf mijn iPhone

**Comment by devnoname120** [comment]
Anyone tried this instead of the Samsung SDK?
https://github.com/imgntn/samsung-smartTV-packager

**Comment by bundy-al** [comment]
devnoname120 the smartTV packager is only for the samsung tv 2013 i think...

**Comment by devnoname120** [comment]
Seems like it will be used in the future: https://github.com/raphaelluchini/popcorntime-smarttv/issues/10

**Comment by raphaelluchini** [comment]
@devnoname120 and @bundy-al , I've released a new version, including grunt packager ;) Please Check this out!

**Comment by bundy-al** [comment]
Hello can you tell me how i get the popcorntime-smarttv on my smart tv. 
Wat most i do with the zip file ?
Or can you help me, you can take over my pc with teamviewer. 
Please a message back. 

Greetz

Verstuurd vanaf mijn iPhone

**Comment by bundy-al** [comment]
Hello Oscar, there is a new popcorntime-smarttv including grunt packager,   

Do you have time to test it on my pc.

You have help me already a few weeks ago.

Greetz Nico

-------Oorspronkelijk bericht-------

Van: Oscar Miranda

Datum: 18-10-2014 20:54:13

Aan: raphaelluchini/popcorntime-smarttv

Cc: bundy-al

Onderwerp: Re: [popcorntime-smarttv] Not working on a Samsung TV Serie D
(#5)

Hello Nico,

How're you?

Yes, I'm available

**Comment by Flconeyes** [comment]
Hello Nico, yes, sure I can help you. I just need to setup a day, couse I'm
working right now.
Regards

**Comment by bundy-al** [comment]
When do you have time to test the new app.

Tomorrow maybe ????

You may say the day and time.

I was so far, that i have the old popcorntime-smarttv on my tv, but its not
working.

But i get a email 2 day's ago from raphaelluchini the maker that there was
new app with including grunt packager .

Greetz and thank you 

-------Oorspronkelijk bericht-------

Van: Oscar Miranda

Datum: 24-11-2014 19:43:37

Aan: raphaelluchini/popcorntime-smarttv

Cc: bundy-al

Onderwerp: Re: [popcorntime-smarttv] Not working on a Samsung TV Serie D
(#5)

Hello Nico, yes, sure I can help you. I just need to setup a day, couse I'm

working right now.

Regards

**Comment by Flconeyes** [comment]
I'm available Wednesday, Thu, Fri, Sat or Sun.
Let me know?!

**Comment by bundy-al** [comment]
Luchini Raphael
Do you have new instructions, how i must install the new popcorntime-smarttv on my Windows 8 x64 to my smarttv step by step. 

Greetz and thank you 

Verstuurd vanaf mijn iPhone

**Comment by bundyal** [comment]
Oscar may i have your personal mailadres, that is better than this way. 

If you can wednesday, send you me a mail how late you have time. 
Greetz

Verstuurd vanaf mijn iPhone

> Op 24 nov. 2014 om 20:07 heeft Oscar Miranda notifications@github.com het volgende geschreven:
> 
> I'm available Wednesday, Thu, Fri, Sat or Sun.
> Let me know?!
>

**Comment by raphaelluchini** [comment]
@bundy-al There's no difference among others OS, just in how to install the dependencies (Node/npm). Anyway, I'll provide a tutorial about this.

**Comment by Flconeyes** [comment]
Nico, if you read this. Send me an email. I have good news. Regards

**Comment by bundyal** [comment]
Hello Oscar, how are you.

Tell me the good news.

I have a question, can we mail personal to each other.

My mailadres is bundyal@ziggo.nl,  may i have yours, then we mail not to the
popcorn smarttv forum.

Greetz nico 

-------Oorspronkelijk bericht-------

Van: Oscar Miranda

Datum: 28-12-2014 17:32:24

Aan: raphaelluchini/popcorntime-smarttv

Cc: bundyal

Onderwerp: Re: [popcorntime-smarttv] Not working on a Samsung TV Serie D
(#5)

Nico, if you read this. Send me an email. I have good news. Regards

**Comment by bundyal** [comment]
Hello, 

Do you allready have a tutorial for this. 

How can i put your smarttv app on my Samsung smart tv ?

Greetz Nico

Verstuurd vanaf mijn iPhone
