### ISSUE TITLE
Stuck on Video loading...

### ISSUE THREAD

**Issue by amirrony** [raphaelluchini/popcorntime-smarttv#6]
I followed you instructions and now I have a working app on my TV.

When starting the App I'm getting list of movies and when selecting one, I get the summary of the movie and when I press the watch button it says "Loading Video" and below the progress bar is says connecting... But nothing happens. 

Tried that on several movies - the same!

I tried closing my firewall on my PC but this didn't help.

Any Idea?
![img_20140623_115345](https://cloud.githubusercontent.com/assets/7962604/3355559/9117a6e4-fab4-11e3-96d0-f32f94dc4b3f.jpg)

**Comment by amirrony** [comment]
BTW, I'm using windows 7 and used the latest Samsung SDK

**Comment by amirrony** [comment]
few things I'v done since...

I switched to SDK 3.5.2
I manage to run torrent reading from my browser on my PC

http://localhost:3000/?torrent=https://yts.re/download/start/D61ABDBD6A17D5FA2F116078A2FA20F02B07AF8F.torrent 

and after: http://localhost:8888

and it worked on my browser.

For some reason, my TV set is not sending the request for a torrent (my pc address is set in player.js line 8)

My tv is the UA46ES6800

**Comment by hlinkpt** [comment]
I have exactly the same problem...  It freezes on the loadingVideo while connecting (the bar never fills). 
When I run node server I get this " Server running on: 192.168.1.101 (localserver). Set this IP in your TV
       app (frontend/player.js line 8) "     I insert the 192.168.1.101 on line 8 (my local server ip that is running node) and upload the app to the TV but it still freezes. I assume the problem must be that node is not sending data but really don't know what to do anymore. Any hints ?

when I do " http://localhost:3000/?torrent=https://yts.re/download/start/D61ABDBD6A17D5FA2F116078A2FA20F02B07AF8F.torrent " On my browser I get this 

Error: Cannot find module 'node-uuid' at Function.Module._resolveFilename (module.js:338:15) at Function.Module._load (module.js:280:25) at Module.require (module.js:364:17) at require (module.js:380:17) at Object.<anonymous> (C:\smarttv\node_modules\peerflix\node_modules\read-torrent\node_modules\request\index.js:28:12) at Module._compile (module.js:456:26) at Object.Module._extensions..js (module.js:474:10) at Module.load (module.js:356:32) at Function.Module._load (module.js:312:12) at Module.require (module.js:364:17)

Thanks in advance - ue40es8000sxxc

**Comment by hlinkpt** [comment]
@raphaelluchini Cara por favor pode dar uma dica. Obrigadão

**Comment by ghost** [comment]
I have the same issue...... Anybody an idea?
@raphaelluchini please help us to use this nice project!!

**Comment by raphaelluchini** [comment]
Hello guys, I'm working hard and as fast I can to launch next new version of popcorntime totally refactored, so, in some days we are be able to push this app forward with bug fixes and more features!

I'm open for any suggestions, PRs, etc!

Thanks

**Comment by raphaelluchini** [comment]
Please, for server issues, use the new server repository.

https://github.com/raphaelluchini/popcorntime-smarttv-server
